// @ts-check

/**
 * Transform markdown by increasing header levels by 1
 * (# becomes ##, ## becomes ###, etc.)
 *
 * This transformer is used to adjust the markdown generated by Copilot CLI
 * conversation.md when displaying it in GitHub Actions step summaries.
 *
 * Rules:
 * - Only transforms ATX-style headers (# prefix)
 * - Preserves whitespace and indentation
 * - Does not transform headers in code blocks
 * - Does not transform headers in inline code
 * - Maximum header level is 6 (h6)
 * - Uses regex for efficient processing
 *
 * @param {string} markdown - Markdown content to transform
 * @returns {string} Transformed markdown with increased header levels
 */
function increaseHeaderLevel(markdown) {
  if (!markdown || typeof markdown !== "string") {
    return markdown || "";
  }

  // Normalize line endings to \n for consistent processing
  const normalizedMarkdown = markdown.replace(/\r\n/g, "\n");

  // Split into lines for processing
  const lines = normalizedMarkdown.split("\n");
  const result = [];
  let inCodeBlock = false;
  let codeBlockFence = "";

  for (const line of lines) {
    // Track code block state (fenced code blocks with ``` or ~~~)
    const fenceMatch = line.match(/^(\s*)(`{3,}|~{3,})/);
    if (fenceMatch) {
      if (!inCodeBlock) {
        // Starting a code block
        inCodeBlock = true;
        codeBlockFence = fenceMatch[2][0]; // Get the fence character (` or ~)
      } else if (line.includes(codeBlockFence.repeat(3))) {
        // Ending a code block (must have at least 3 fence chars)
        inCodeBlock = false;
        codeBlockFence = "";
      }
      result.push(line);
      continue;
    }

    // If we're in a code block, don't transform
    if (inCodeBlock) {
      result.push(line);
      continue;
    }

    // Check if this line is an ATX-style header (# prefix)
    // Pattern: optional whitespace, 1-6 #, at least one space, then content
    const headerMatch = line.match(/^(\s*)(#{1,6})(\s+.*)$/);
    if (headerMatch) {
      const indent = headerMatch[1];
      const hashes = headerMatch[2];
      const content = headerMatch[3];

      // Only increase if we're below h6 (6 hashes)
      if (hashes.length < 6) {
        result.push(`${indent}#${hashes}${content}`);
      } else {
        // Already at max level, keep as-is
        result.push(line);
      }
    } else {
      // Not a header, keep as-is
      result.push(line);
    }
  }

  return result.join("\n");
}

module.exports = {
  increaseHeaderLevel,
};
